# frozen_string_literal: true

require "rouge"

module Blusher
  # The rouge-API drop-in: route every `RegexLexer#lex` through carmine when a
  # table exists AND carmine handles the input natively; otherwise fall back to
  # rouge unchanged. Zero-divergence by construction — carmine either returns a
  # byte-identical token stream or declines.
  module Shim
    # qualified rouge token name ("Name.Builtin") → the Token object.
    QUALNAME = {}
    Rouge::Token.each_token { |t| QUALNAME[t.qualname] = t }
    QUALNAME.freeze

    # qualified token name → rouge HTML shortname ("Name.Function" → "nf",
    # "Text" → ""). Passed to the fused Rust formatter so the whole lex+format
    # pipeline produces one HTML String without materializing Ruby tokens.
    SHORTNAME = {}
    Rouge::Token.each_token { |t| SHORTNAME[t.qualname] = t.shortname if t.shortname }
    SHORTNAME.freeze

    # A deferred token stream: returned by the patched `RegexLexer#lex` when no
    # block is given, so the lexer + source travel together to the formatter.
    # `Rouge::Formatters::HTML#format` can then fuse lex+format in Rust (one
    # String, no per-token Ruby objects). Any OTHER consumer just iterates it —
    # `#each` lexes via carmine on demand, yielding the same [Token, value]
    # pairs rouge would, so it is a transparent drop-in for `lex`'s old return.
    class TokenStream
      include Enumerable
      attr_reader :lexer, :source

      def initialize(lexer, source)
        @lexer = lexer
        @source = source
      end

      def tag
        @lexer.class.tag
      end

      def each(&b)
        return enum_for(:each) unless b
        toks = Blusher::Native.lex(tag, Shim.table_for(tag), @source, QUALNAME)
        toks ||= @lexer.__blusher_rouge_lex(@source).to_a
        toks.each(&b)
      end
    end

    @dir = File.expand_path("tables", __dir__)
    @cache = {}
    @routable = {}

    class << self
      # Directory of per-lexer carmine tables (`<tag>.json`). Generated by
      # `rake tables` (carmine's tools/extract.rb over the installed rouge).
      attr_accessor :dir

      def table_for(tag)
        return @cache[tag] if @cache.key?(tag)
        path = File.join(@dir, "#{tag}.json")
        @cache[tag] = (File.read(path) if File.exist?(path))
      end

      # Whether a table is worth attempting natively. A table that contains a
      # `callback` rule (rouge procs / recursion that carmine can't execute)
      # DECLINES the moment that rule is reached — and then rouge re-lexes the
      # whole input from scratch, so the carmine attempt was pure wasted work.
      # For a performance drop-in that net-loses, so we skip such lexers up
      # front and let rouge own them. Verdict is a cheap substring scan over
      # the raw table JSON (no parse), cached per tag. Zero-divergence holds:
      # callback-free tables never decline, skipped tables run rouge verbatim.
      def routable?(tag)
        return @routable[tag] if @routable.key?(tag)
        table = table_for(tag)
        @routable[tag] = !table.nil? && !table.include?('"kind":"callback"')
      end
    end
  end
end

module Rouge
  class RegexLexer
    # Install once (idempotent if the gem is required twice).
    unless method_defined?(:__blusher_rouge_lex)
      alias_method :__blusher_rouge_lex, :lex

      def lex(string, opts = nil, &b)
        tag = self.class.tag
        # :continue (incremental relex) isn't expressible against carmine — and
        # non-routable lexers gain nothing — so hand those straight to rouge.
        return __blusher_rouge_lex(string, opts, &b) if (opts && opts[:continue]) ||
                                                         !Blusher::Shim.routable?(tag)

        if b
          # Block form (the caller wants tokens now): lex via carmine and stream.
          toks = Blusher::Native.lex(tag, Blusher::Shim.table_for(tag), string, Blusher::Shim::QUALNAME)
          return toks ? toks.each(&b) : __blusher_rouge_lex(string, opts, &b)
        end

        # No block: defer, so HTML#format can fuse lex+format in Rust.
        Blusher::Shim::TokenStream.new(self, string)
      end
    end
  end

  module Formatters
    class HTML
      # Fuse lex+format for the common, hot path — `Rouge.highlight`/Jekyll do
      # `formatter.format(lexer.lex(src))`. When the tokens are a deferred
      # blusher TokenStream and this is an unadorned HTML formatter (escape
      # disabled, no streaming block, exact class — subclasses like HTMLInline
      # render differently), carmine lexes AND formats in Rust, returning one
      # HTML String. Otherwise (or if carmine declines) fall back to rouge's
      # formatter over the iterated stream — byte-identical either way.
      unless method_defined?(:__blusher_html_format)
        alias_method :__blusher_html_format, :format

        def format(tokens, &b)
          if !b &&
             instance_of?(Rouge::Formatters::HTML) &&
             !Rouge::Formatter.escape_enabled? &&
             tokens.is_a?(Blusher::Shim::TokenStream)
            html = Blusher::Native.format_html(
              tokens.tag, Blusher::Shim.table_for(tokens.tag), tokens.source, Blusher::Shim::SHORTNAME
            )
            return html if html
          end
          __blusher_html_format(tokens, &b)
        end
      end
    end
  end
end
